theme: jekyll-theme-minimal

title: Dr. Tobias Füchslin
description: Research & Reporting Expert
logo: /assets/img/profile.jpg

author:
  name: Dr. Tobias Füchslin
  email: tobias.fuechslin@gmail.com
social_links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/tobias-fuechslin-research/
  - title: Google Scholar
    url: https://scholar.google.com/citations?user=JyvHMUMAAAAJ&hl=de

show_downloads: false

github:
  is_project_page: false

lang: en
